name: Workflow for Codecov example-python
permissions:
  id-token: write
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov app --junitxml=junit.xml -o junit_family=legacy
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: getsentry/prevent-action@latest
