name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov app --junitxml=junit.xml -o junit_family=legacy
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        run: |
          curl -LOs https://github.com/getsentry/prevent-cli/releases/latest/download/sentry-prevent-cli_linux_arm64

          chmod u+x ./sentry-prevent-cli_linux-arm64
          ./sentry-prevent-cli_linux_arm64 -v upload --report-type test-results
        env:
          PREVENT_TOKEN: ${{ secrets.PREVENT_TOKEN }}
